# Generated by fusen: do not edit by hand

#' Formatage du dataset AGRITOX en une table d'attributs par SA
#'
#' @param x dataframe jeu de données à formater
#' @param source_name char Nom de la source à afficher
#' @param modified_date date Nom de la source à afficher
#'
#' @return
#' tibble
#' @export
#'
#' @examples
# Fonction de formatage du dataset AGRITOX

#' # Lecture du dataset AGRITOX
#' agritox_path <- system.file("agritox/", package = "RefPesticidesBzh")
#' agritox <- RefPesticidesBzh::load_dataset(path=agritox_path, pattern="*.csv", encoding = "Latin-1")
#' 
#' # Ajout de la date de mise à jour à partir de la fiche Data.gouv
#' agritox$mise_a_jour <- RefPesticidesBzh::metadonnees_dataset('https://www.data.gouv.fr/fr/datasets/base-de-donnees-agritox/')$`Modifiée.le` %>% as.Date("%d %b %Y")
#' 
#' # Mise en forme de la liste des SA avec les attributs retenus pour cette source
#' agritox_sa <- agritox %>% format_agritox(source_name = "AGRITOX", modified_date = agritox$mise_a_jour)
#' 
format_agritox <- function(x, source_name, modified_date){
x$agritox_identite %>%
  left_join(select(x$agritox_ecotoxicite, `Numéro.CAS`, `Valeur.PNEC`), by = c("N..CAS" = "Numéro.CAS")) %>%
  as.tibble() %>% 
  select(
    SA_CodeCAS = N..CAS,
    SA_Libelle = NOM.SA,
    SA_PNEC = Valeur.PNEC
  )%>%
  mutate(source = source_name,
         mise_a_jour = modified_date)
}


#' Téléchargement et décompression du dataset depuis une url
#'
#' @param url char url stable du jeu de données
#' @param name char nom du dataset
#' @param format char format du fichier téléchargé (zip, xls, csv)
#'
#'
#' @return
#' Aucune reponse - Les fichiers sont téléchargés et dézippés dans le dossier extdata/
#' @export
#'
#' @examples
# Fonction d'import d'un dataset à partir d'un fichier téléchargeable

#' # Téléchargement du dataset agritox
#' import_dataset(url='https://www.data.gouv.fr/fr/datasets/r/ce799eee-2cc4-4406-b4b4-318ea35cd5e8', name="agritox", format="zip")
#' 
#' # Téléchargement du dataset ephy
#' import_dataset(url='https://www.data.gouv.fr/fr/datasets/r/98f7cac6-6b29-4859-8739-51b825196959', name="ephy", format="zip")
#' 
#' # Téléchargement du dataset "Description des substances actives phytosanitaires" de l'OEB
#' import_dataset(url='http://gide.bretagne-environnement.org/index.php/content/download/25084/384395/file/oeb_referentiels_substances_actives.csv', name="oeb", format="csv")
#' 
#' # Les fichiers sont téléchargés dans les sous-dossiers du répertoire de travail
import_dataset <- function(url, name, format){
  
  folder <- paste0(name)
  file <- paste0(name,"/",name,".",format)
  
  if (!dir.exists(folder)) {dir.create(folder, recursive = TRUE)}
  download.file(url, file, mode='wb')
  
  # unzip
  if(format == "zip"){
    unzip(zipfile = file, exdir=folder)
  }
}

#' Lecture d'un dataset importé
#'
#' @param path char chemin vers le répertoire des fichiers à charger
#' @param pattern char motif de sélection des fichiers
#' @param encoding char encodage des fichiers
#'
#' @return
#' Liste contenant les tables lues dans chaque fichier correspondant au motif
#' @export
#'
#' @examples
# Fonction de lecture d'un dataset importé et dézippé dans son dossier data/nom_du_dataset

#' 
#' agritox_path <- system.file("agritox/", package = "RefPesticidesBzh")
#' agritox_raw <- RefPesticidesBzh::load_dataset(path=agritox_path, pattern="*.csv", encoding = "UTF-8")
#' 
load_dataset <- function(path, pattern = "*.csv", encoding = "UTF-8"){
  
list <- list.files(path = path, pattern=pattern, full.names = TRUE) %>%
  purrr::map(~read.csv(.x, sep=";", encoding = encoding))

names(list) <- list.files(path = path, pattern=pattern, full.names = FALSE) %>%
  stringr::str_remove(".csv")%>%
  tolower()

list%>%
  return()
}

#' Metadonnées du dataset
#'
#' @param url char url de la fiche data.gouv.fr
#'
#' @import magrittr
#'
#' @return
#' tibble des métadonnées du jeu de données
#' @export
#'
#' @examples
# Fonction de lecture des métadonnées du jeu de données depuis la page data.gouv.fr

#' metadonnees_dataset('https://www.data.gouv.fr/fr/datasets/base-de-donnees-agritox/')
metadonnees_dataset <- function(url){

  page <- rvest::read_html(url)

if (grepl('data.gouv.fr/fr/datasets/', url, fixed = TRUE)){

metadonnee <- page %>% 
  rvest::html_elements(".ressources .description-list div dd")%>% 
  rvest::html_text2()%>%t()

colnames(metadonnee) <- page %>% 
  rvest::html_elements(".ressources .description-list div dt") %>% 
  rvest::html_text2()%>%make.names()
}

metadonnee%>%tibble::as_tibble()
}
